name: todos
description: Flutter Data TO-DOs sample app
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  hooks_riverpod: ^1.0.0
  uuid: ^3.0.4
  flutter_data: ^1.0.0
  json_annotation: ^4.3.0
  path_provider: ^2.0.2

# dependency_overrides:
#   flutter_data:
#     path: ../flutter_data

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.1
  json_serializable: ^6.0.0

flutter:
  uses-material-design: true
