name: todos
description: Flutter Data TO-DOs sample app
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  hooks_riverpod: ^0.12.4
  uuid: ^2.0.4
  flutter_data: ^0.7.0-rc1
  json_annotation: ^3.0.1
  path_provider: ^1.6.7

# dependency_overrides:
#   flutter_data:
#     path: ../flutter_data

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.1
  json_serializable: ^3.3.0

flutter:
  uses-material-design: true
